### ISSUE TITLE
Null value for Prefix and Suffix

### ISSUE THREAD

**Issue by ManojKiranA** [AAbosham/filament-spark-pie#3]
Is there any way we can set `prefix` and `suffix` to `null`

**Comment by AAbosham** [comment]
Thanks for reporting for now you can use empty string like `->suffix('')`, I will make an update to solve this.

**Comment by AAbosham** [comment]
[v0.0.3](https://github.com/AAbosham/filament-spark-pie/releases/tag/v0.0.3) Fixed

**Comment by ManojKiranA** [comment]
will give it a try and let you know
